[2025-04-17 20:00:09] ERROR eduvmstore_logger: Access denied for user: 78ce4245-a2a7-41f4-abc6-3bd7f7082c62
[2025-04-17 20:00:09] ERROR eduvmstore_logger: Access denied for user: 78ce4245-a2a7-41f4-abc6-3bd7f7082c62
[2025-04-17 20:00:09] ERROR eduvmstore_logger: OpenStack Authentication Token missing
[2025-04-17 20:02:24] ERROR eduvmstore_logger: Keystone token validation request failed: HTTPConnectionPool(host='141.72.12.111', port=80): Max retries exceeded with url: /identity/v3/auth/tokens (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x103b0d400>, 'Connection to 141.72.12.111 timed out. (connect timeout=None)'))
[2025-04-17 20:02:24] ERROR eduvmstore_logger: Invalid token
[2025-04-17 20:02:38] ERROR eduvmstore_logger: Keystone token validation request failed: HTTPConnectionPool(host='141.72.12.111', port=80): Max retries exceeded with url: /identity/v3/auth/tokens (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x103c70690>, 'Connection to 141.72.12.111 timed out. (connect timeout=None)'))
[2025-04-17 20:02:38] ERROR eduvmstore_logger: Invalid token
[2025-04-17 20:02:55] ERROR eduvmstore_logger: Keystone token validation request failed: HTTPConnectionPool(host='141.72.12.111', port=80): Max retries exceeded with url: /identity/v3/auth/tokens (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x103c71310>, 'Connection to 141.72.12.111 timed out. (connect timeout=None)'))
[2025-04-17 20:02:55] ERROR eduvmstore_logger: Invalid token
[2025-04-17 20:03:26] ERROR eduvmstore_logger: Keystone token validation request failed: HTTPConnectionPool(host='141.72.12.111', port=80): Max retries exceeded with url: /identity/v3/auth/tokens (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x103b5dba0>, 'Connection to 141.72.12.111 timed out. (connect timeout=None)'))
[2025-04-17 20:03:26] ERROR eduvmstore_logger: Invalid token
